[book]
authors = ["epwalsh"]
language = "en"
multilingual = false
src = "src"
title = "Rusty Celery"

[output.html]
default-theme = "Ayu"
git-repository-url = "https://github.com/rusty-celery/rusty-celery.github.io"
