on:
  push:
    branches:
      - code
name: Build and deploy on push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install mdBook
        run: |
          wget 'https://github.com/rust-lang/mdBook/releases/download/v0.3.5/mdbook-v0.3.5-x86_64-unknown-linux-gnu.tar.gz' --output-document 'mdbook.tar.gz'
          tar -zxvf mdbook.tar.gz
          ls

      - name: Build
        run: ./mdbook build

      - name: Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: book
          GITHUB_PAC: ${{ secrets.TOKEN }}
